name: Lint

on:
  push:
    branches: [main]
    paths:
      - "README.md"
      - ".markdownlint.json"
  pull_request:
    paths:
      - "README.md"
  workflow_dispatch:

permissions: read-all

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
        with:
          globs: "README.md"
          config: ".markdownlint.json"
