name: pre-commit-autoupdate

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.x"
      - run: pip install pre-commit==4.1.0
      - run: pre-commit autoupdate
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: pre-commit autoupdate"
          title: "chore: pre-commit autoupdate"
          body: Automated pre-commit hook bump.
          branch: chore/pre-commit-autoupdate
          delete-branch: true
          labels: dependencies,automated
