name: pre-commit-autoupdate

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v6
        with:
          python-version: "3.x"
      - run: pip install pre-commit==4.1.0
      - run: pre-commit autoupdate
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: pre-commit autoupdate"
          title: "chore: pre-commit autoupdate"
          body: Automated pre-commit hook bump.
          branch: chore/pre-commit-autoupdate
          delete-branch: true
          labels: dependencies,automated
